dist:
  name: my-otelcol
  description: Basic OTel Collector distribution for Developers
  output_path: ./
  version: 1.0.0
  module: Bikara950225/my-otelcol

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.75.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.75.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.75.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.75.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.75.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.75.0
