receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-prometheus'
          static_configs:
            - targets: ['172.30.0.89:8269']
exporters:
  prometheus:
    endpoint: localhost:8889

processors:
  batch:
    timeout: 1s

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
      processors: [batch]
